/**
 * JSON Schema for `naijacloud.json`, and the `naijacloud schema` command.
 *
 * The schema is *generated from the zod object that validates the file*, so the
 * two cannot drift: what an editor autocompletes is exactly what the CLI
 * accepts. `npm run build` writes the same document to
 * `schema/naijacloud.schema.json`, which ships inside the package.
 *
 * There is no hosted schema URL on purpose. Completion should work offline,
 * behind a proxy, and for a CLI release that is a few versions old — a remote
 * `$ref` gives none of that, and would pin every repo to whatever the website
 * happens to be serving rather than to the binary that parses the file.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import process from "node:process";

import { z } from "zod";

import { CLIENT_VERSION } from "../api/index.js";
import { LOCAL_SCHEMA_PATH, MANIFEST_FILENAME, STATE_DIR, manifestSchema } from "../deploy-static/manifest.js";
import { write } from "../terminal.js";

/** Builds the JSON Schema document for the manifest. */
export function manifestJsonSchema(): Record<string, unknown> {
  // `io: "input"` describes what may be *written* in the file, which is what an
  // editor validates against.
  const generated = z.toJSONSchema(manifestSchema, { io: "input" }) as Record<string, unknown>;

  return {
    ...generated,
    title: `NaijaCloud deploy manifest (${MANIFEST_FILENAME})`,
    "x-generated-by": `naijacloud-cli/${CLIENT_VERSION}`,
  };
}

export function schemaJson(): string {
  return `${JSON.stringify(manifestJsonSchema(), null, 2)}\n`;
}

/**
 * Writes the editor copy next to the manifest, plus a `.gitignore` that hides
 * the whole state directory.
 *
 * Ignoring itself is deliberate: the alternative is editing the user's root
 * `.gitignore`, and a tool that rewrites a file it does not own is a tool people
 * stop trusting. Returns the path written, relative to `dir`.
 */
export function writeLocalSchema(dir: string): string {
  const target = join(dir, LOCAL_SCHEMA_PATH);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, schemaJson(), "utf8");
  writeFileSync(
    join(dir, STATE_DIR, ".gitignore"),
    "# Generated by the NaijaCloud CLI; not meant to be committed.\n*\n",
    "utf8",
  );
  return LOCAL_SCHEMA_PATH;
}

/**
 * `naijacloud schema` — print the JSON Schema, or write the local copy.
 *
 * `--write` with no value writes `.naijacloud/schema.json`; `--write <path>`
 * puts it wherever the caller wants, for teams that would rather commit it.
 */
export function schemaCommand(options: { write?: string | undefined }): void {
  if (options.write === undefined) {
    process.stdout.write(schemaJson());
    return;
  }

  if (options.write === "") {
    const written = writeLocalSchema(process.cwd());
    write(`Wrote ${written}\n`);
    return;
  }

  const target = resolve(process.cwd(), options.write);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, schemaJson(), "utf8");
  write(`Wrote ${target}\n`);
}
